# Generated by Django 5.1.4 on 2024-12-28 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان درسته بندی')),
                ('url', models.CharField(db_index=True, max_length=100, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productcategory', verbose_name='دست بندی والد')),
            ],
            options={
                'verbose_name': 'products_category',
                'verbose_name_plural': 'products_categorise',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان محصول')),
                ('url_title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان در url')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('image', models.ImageField(upload_to='images/products', verbose_name='تصویر اصلی')),
                ('short_description', models.TextField(verbose_name='توضحات کوتاه محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default='', max_length=400, unique=True, verbose_name='slug')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('category', models.ManyToManyField(to='product_module.productcategory', verbose_name='دیته بندی')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': "product's",
            },
        ),
    ]
