# Generated by Django 5.1.4 on 2024-12-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='url',
            field=models.CharField(db_index=True, max_length=100, verbose_name='عنوان در url'),
        ),
    ]
