# Generated by Django 5.1.4 on 2024-12-28 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_productvisit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvisit',
            options={'verbose_name': 'article_visit', 'verbose_name_plural': 'article_visits'},
        ),
    ]
