# Generated by Django 5.1.4 on 2024-12-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_alter_productcategory_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'products_category', 'verbose_name_plural': 'products_categorise'},
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', max_length=400, unique=True),
        ),
    ]
