# Generated by Django 5.1.4 on 2024-12-28 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_alter_productvisit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvisit',
            options={'verbose_name': 'product_visit', 'verbose_name_plural': 'product_visits'},
        ),
    ]
