# Generated by Django 5.1.4 on 2024-12-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_alter_product_image_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_four',
            field=models.ImageField(null=True, upload_to='images/products', verbose_name='تصویر اضافه'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_main',
            field=models.ImageField(default='test', upload_to='images/products', verbose_name='تصویر اصلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_sec',
            field=models.ImageField(null=True, upload_to='images/products', verbose_name='تصویر اضافه'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_third',
            field=models.ImageField(null=True, upload_to='images/products', verbose_name='تصویر اضافه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', max_length=400, unique=True, verbose_name='slug'),
        ),
    ]
