# Generated by Django 5.1.4 on 2024-12-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_alter_productvisit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.CharField(blank=True, choices=[('flaticon-029-cupcake-3', 'Cupcake 3'), ('flaticon-034-chocolate-roll', 'Chocolate Roll'), ('flaticon-005-pancake', 'Pancake'), ('flaticon-030-cupcake-2', 'Cupcake 2'), ('flaticon-006-macarons', 'Macarons')], default='flaticon-006-macarons', max_length=50, null=True, verbose_name='آیکون'),
        ),
    ]
