# Generated by Django 5.1.4 on 2024-12-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_remove_product_image_product_image_four_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='تصویر اضافه'),
        ),
    ]
