# Generated by Django 5.1.4 on 2024-12-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_product_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='حداقل مقدار خرید'),
        ),
    ]
