# Generated by Django 5.1.4 on 2024-12-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_site_slider_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_settings',
            name='short_description',
            field=models.TextField(default='test', verbose_name='توضیحات کوتاه'),
            preserve_default=False,
        ),
    ]
