# Generated by Django 5.1.4 on 2024-12-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال شده')),
                ('response', models.TextField(verbose_name='جواب')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='ادمین برسی کرد')),
            ],
            options={
                'verbose_name': 'contact us',
                'verbose_name_plural': 'contact us',
            },
        ),
    ]
