# Generated by Django 5.1.4 on 2024-12-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback_model',
            options={'verbose_name': 'feedback', 'verbose_name_plural': 'feedbacks'},
        ),
    ]
