# Generated by Django 5.1.4 on 2024-12-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_alter_feedback_model_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_model',
            name='rating',
            field=models.PositiveIntegerField(default=1, verbose_name='امتیاز (1 تا 5)'),
        ),
    ]
