# Generated by Django 5.1.4 on 2024-12-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_feedback_model_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/Gallery', verbose_name='تصویر')),
                ('image_two', models.ImageField(upload_to='images/Gallery', verbose_name='تصویر')),
                ('image_tree', models.ImageField(upload_to='images/Gallery', verbose_name='تصویر')),
                ('image_four', models.ImageField(upload_to='images/Gallery', verbose_name='تصویر')),
                ('image_five', models.ImageField(upload_to='images/Gallery', verbose_name='تصویر')),
                ('image_six', models.ImageField(upload_to='images/Gallery', verbose_name='تصویر')),
            ],
        ),
    ]
