# Generated by Django 5.1.4 on 2024-12-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0004_gallery_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery_model',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='فعال'),
        ),
    ]
