# Generated by Django 5.1.4 on 2024-12-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(default='tst', max_length=150, verbose_name='عنوان (en) '),
            preserve_default=False,
        ),
    ]
