# Generated by Django 5.1.4 on 2024-12-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0004_rename_url_articlecategory_url_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecategory',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='url',
        ),
        migrations.AddField(
            model_name='article',
            name='url_title',
            field=models.CharField(default='test', max_length=150, verbose_name='عنوان در url '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='url_title',
            field=models.CharField(max_length=150, verbose_name='عنوان در url '),
        ),
    ]
