# Generated by Django 5.1.4 on 2024-12-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_rename_name_articlecategory_title_remove_article_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url_title',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='عنوان در url '),
        ),
    ]
