# Generated by Django 5.1.4 on 2024-12-23 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0006_alter_article_url_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='article_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='متن کامنت')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت کامنت')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_module.article', verbose_name='مقاله')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_module.article_comments', verbose_name='کامنت والد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده کامنت')),
            ],
            options={
                'verbose_name': 'Article_comment',
                'verbose_name_plural': 'Article_comments',
            },
        ),
    ]
