# Generated by Django 5.1.4 on 2024-12-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0008_alter_article_comments_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_detail_one',
            field=models.ImageField(blank=True, null=True, upload_to='images/article', verbose_name='تصویر برای جزییات مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_detail_two',
            field=models.ImageField(blank=True, null=True, upload_to='images/article', verbose_name='تصویر برای جزییات مقاله'),
        ),
    ]
