# Generated by Django 5.1.4 on 2024-12-28 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0011_rename_product_articlevisited_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlevisited',
            options={'verbose_name': 'article_visit', 'verbose_name_plural': 'article_visits'},
        ),
    ]
