# Generated by Django 5.1.4 on 2024-12-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='فارغ التحصیلان', max_length=250, verbose_name='آدرس کاربر'),
            preserve_default=False,
        ),
    ]
