# Generated by Django 5.1.4 on 2024-12-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_alter_user_options_alter_user_about_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='کد فعالسازی ایمیل'),
        ),
    ]
